spring:
  application:
    name: Todo-api
  datasource:
    url: jdbc:h2:mem:todo
    user: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console